using System.Drawing;

namespace Sicavi.WinForms.Forms;

partial class LoginForm
{
    private TextBox _usernameTextBox = null!;
    private TextBox _passwordTextBox = null!;
    private CheckBox _showPasswordCheckBox = null!;
    private Button _loginButton = null!;
    private Button _registerButton = null!;
    private Label _statusLabel = null!;

    private void InitializeComponent()
    {
        var brandPanel = new Panel();
        var brandTitle = new Label();
        var brandSubtitle = new Label();
        var accent = new Panel();
        var contentPanel = new Panel();
        var title = new Label();
        var subtitle = new Label();
        var userLabel = new Label();
        var passwordLabel = new Label();
        _usernameTextBox = new TextBox();
        _passwordTextBox = new TextBox();
        _showPasswordCheckBox = new CheckBox();
        _loginButton = new Button();
        _registerButton = new Button();
        _statusLabel = new Label();
        SuspendLayout();
        brandPanel.BackColor = Color.FromArgb(13, 22, 32);
        brandPanel.Dock = DockStyle.Left;
        brandPanel.Size = new Size(300, 480);
        brandPanel.Controls.Add(brandTitle);
        brandPanel.Controls.Add(brandSubtitle);
        brandPanel.Controls.Add(accent);
        accent.BackColor = Color.FromArgb(26, 200, 218);
        accent.Location = new Point(36, 116);
        accent.Size = new Size(74, 5);
        brandTitle.Font = new Font("Segoe UI Semibold", 31F, FontStyle.Bold);
        brandTitle.ForeColor = Color.FromArgb(26, 200, 218);
        brandTitle.Location = new Point(32, 136);
        brandTitle.Size = new Size(230, 62);
        brandTitle.Text = "SICAVI";
        brandSubtitle.Font = new Font("Segoe UI", 11F);
        brandSubtitle.ForeColor = Color.FromArgb(157, 172, 189);
        brandSubtitle.Location = new Point(36, 206);
        brandSubtitle.Size = new Size(222, 98);
        brandSubtitle.Text = "Sistema de Inspección y Clasificación Automática por Visión";
        contentPanel.BackColor = Color.FromArgb(24, 34, 47);
        contentPanel.Dock = DockStyle.Fill;
        contentPanel.Controls.Add(title);
        contentPanel.Controls.Add(subtitle);
        contentPanel.Controls.Add(userLabel);
        contentPanel.Controls.Add(_usernameTextBox);
        contentPanel.Controls.Add(passwordLabel);
        contentPanel.Controls.Add(_passwordTextBox);
        contentPanel.Controls.Add(_showPasswordCheckBox);
        contentPanel.Controls.Add(_loginButton);
        contentPanel.Controls.Add(_registerButton);
        contentPanel.Controls.Add(_statusLabel);
        title.Font = new Font("Segoe UI Semibold", 23F, FontStyle.Bold);
        title.ForeColor = Color.White;
        title.Location = new Point(52, 42);
        title.Size = new Size(390, 50);
        title.Text = "Acceso de operador";
        subtitle.ForeColor = Color.FromArgb(157, 172, 189);
        subtitle.Location = new Point(56, 94);
        subtitle.Size = new Size(360, 27);
        subtitle.Text = "Identifícate antes de operar la planta";
        userLabel.ForeColor = Color.FromArgb(190, 203, 216);
        userLabel.Location = new Point(56, 145);
        userLabel.Size = new Size(330, 24);
        userLabel.Text = "USUARIO";
        _usernameTextBox.BackColor = Color.FromArgb(10, 18, 27);
        _usernameTextBox.BorderStyle = BorderStyle.FixedSingle;
        _usernameTextBox.Font = new Font("Segoe UI", 12F);
        _usernameTextBox.ForeColor = Color.White;
        _usernameTextBox.Location = new Point(56, 172);
        _usernameTextBox.Size = new Size(360, 34);
        passwordLabel.ForeColor = Color.FromArgb(190, 203, 216);
        passwordLabel.Location = new Point(56, 225);
        passwordLabel.Size = new Size(330, 24);
        passwordLabel.Text = "CLAVE";
        _passwordTextBox.BackColor = Color.FromArgb(10, 18, 27);
        _passwordTextBox.BorderStyle = BorderStyle.FixedSingle;
        _passwordTextBox.Font = new Font("Segoe UI", 12F);
        _passwordTextBox.ForeColor = Color.White;
        _passwordTextBox.Location = new Point(56, 252);
        _passwordTextBox.Size = new Size(360, 34);
        _passwordTextBox.UseSystemPasswordChar = true;
        _showPasswordCheckBox.AutoSize = true;
        _showPasswordCheckBox.ForeColor = Color.FromArgb(157, 172, 189);
        _showPasswordCheckBox.Location = new Point(56, 294);
        _showPasswordCheckBox.Text = "Mostrar clave";
        _showPasswordCheckBox.CheckedChanged += ShowPasswordCheckBox_CheckedChanged;
        _loginButton.BackColor = Color.FromArgb(26, 200, 218);
        _loginButton.FlatAppearance.BorderSize = 0;
        _loginButton.FlatStyle = FlatStyle.Flat;
        _loginButton.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
        _loginButton.ForeColor = Color.FromArgb(8, 35, 43);
        _loginButton.Location = new Point(56, 332);
        _loginButton.Size = new Size(360, 42);
        _loginButton.Text = "INGRESAR";
        _loginButton.Click += LoginButton_Click;
        _registerButton.FlatStyle = FlatStyle.Flat;
        _registerButton.FlatAppearance.BorderColor = Color.FromArgb(72, 95, 121);
        _registerButton.ForeColor = Color.FromArgb(210, 221, 232);
        _registerButton.Location = new Point(56, 383);
        _registerButton.Size = new Size(360, 36);
        _registerButton.Text = "Registrar nuevo operador";
        _registerButton.Click += RegisterButton_Click;
        _statusLabel.ForeColor = Color.FromArgb(255, 105, 105);
        _statusLabel.Location = new Point(56, 425);
        _statusLabel.Size = new Size(360, 42);
        _statusLabel.TextAlign = ContentAlignment.TopCenter;
        AcceptButton = _loginButton;
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(24, 34, 47);
        ClientSize = new Size(780, 480);
        Controls.Add(contentPanel);
        Controls.Add(brandPanel);
        Font = new Font("Segoe UI", 10F);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "LoginForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "SICAVI · Inicio de sesión";
        ResumeLayout(false);
    }
}
